# File: tooling.mk
# Author: Amlal El Mahrouss
# Purpose: Generate OCAML tools.
# (C) 2026 Amlal El Mahrouss.
# Licensed under Apache 2.0.

CAML=ocamlopt

.PHONY: tooling
tooling: 
	$(CAML) addpaper.ml
	$(CAML) addentry.ml